name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true

      - name: Build Windows Executable
        env:
          GOOS: windows
          GOARCH: amd64
          URL: ${{ secrets.URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          FILE_PATH: ${{ secrets.FILE_PATH }}
        run: go build -v -o maple-downloader.exe ./...

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: maple-windows-executable
          path: maple-downloader.exe
          retention-days: 7

      - name: Generate release tag
        id: tag
        run: |
          echo "release_tag=v$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_OUTPUT

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          name: Release ${{ steps.tag.outputs.release_tag }}
          draft: false
          prerelease: false
          files: maple-downloader.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}