name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate version
        id: version
        run: |
          VERSION="v$(date +'%Y.%m.%d.%H%M')"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true

      - name: Build Windows Executable
        env:
          GOOS: windows
          GOARCH: amd64
          URL: ${{ secrets.URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          FILE_PATH: ${{ secrets.FILE_PATH }}
        run: go build -v -o "maple-downloader-${{ env.VERSION }}.exe" -ldflags "-X main.URL=${{ secrets.URL }} -X main.USERNAME=${{ secrets.USERNAME }} -X main.PASSWORD=${{ secrets.PASSWORD }}" ./...

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: maple-windows-executable
          path: maple-downloader-${{ env.VERSION }}.exe
          retention-days: 7

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          files: maple-downloader-${{ env.VERSION }}.exe
          token: ${{ secrets.GITHUB_TOKEN }}